
apiVersion: kubeflow.org/v2beta1
kind: MPIJob
metadata:
  name: hpl-mpi
spec:
  slotsPerWorker: 54
  runPolicy:
    cleanPodPolicy: Running
  mpiReplicaSpecs:
    Launcher:
      replicas: 1
      template:
        spec:
          containers:
          - image: ghcr.io/crambor/hpl:v0.2.1
          # - image: ghcr.io/crambor/hpl:hpl-testhpcg
            env:
              - name: OMP_NUM_THREADS
                value: "1"
              - name: OMP_PROC_BIND
                value: "TRUE"
              - name: OMP_PLACES
                value: "cores"


            name: hpl
            # command: ["/bin/bash","-c", "cat HPL.dat && mpirun --allow-run-as-root --bind-to core -np 1 ./xhpl"]
            # command: ["/bin/bash","-c", "mpirun --allow-run-as-root --bind-to core -np 3 ./xhpl && cd ../../hpcg/build/bin/ && mpirun -np 1 --allow-run-as-root ./xhpcg 104 104 104 && ls"]
            command:
            - mpirun
            args:
            - --allow-run-as-root
            - --bind-to-core
            - -np
            - "1"
            - ./xhpl

    Worker:
      replicas: 1
      template:
        spec:
          containers:
          - image: ghcr.io/crambor/hpl:v0.2.1
          # - image: ghcr.io/crambor/hpl:hpl-testhpcg
            name: hpl
            volumeMounts:
            - name: "config"
              mountPath: "/home/mpiuser/hpl/testing/HPL.dat"
              subPath: "HPL.dat"
    
            resources:
              requests:
                cpu: 54
              limits:
                cpu: 54
                memory: 100Gi

          volumes:
          - name: "config"
            configMap:
              name: "config"
